name: CI
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
      - name: java version
        run: java -version
      - name: maven version
        run: mvn --version
      - name: python version
        run: python --version
      - name: docker version
        run: docker -v
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6   # or the version you need
      - name: Verify Terraform version
        run: terraform -version
     

